### ISSUE TITLE
on npm command: `/run/secrets/db_password`: No such file or directory

### ISSUE THREAD

**Issue by ahdinosaur** [Coop-Cloud/peertube#1] opened 2021-07-03 00:33 UTC
hi, thanks for your great work, thanks to this app i'm now hosting a PeerTube service for my creative community: https://tube.arthack.nz/

i ran into a bug, when i try to run an npm command. (which i noticed in the `abra.sh` script)

for example: :bug: 

```shell
abra app arthack-peertube npm create-transcoding-job -- -v "73a5cb03-b7ec-4e43-aec7-faa71213bd92" -r 420
```

returns

```txt
cat: /run/secrets/db_password: No such file or directory

> peertube@3.2.1 create-transcoding-job /app
> node ./dist/scripts/create-transcoding-job.js "-v" "73a5cb03-b7ec-4e43-aec7-faa71213bd92" "-r" "420"

ConnectionError [SequelizeConnectionError]: password authentication failed for user "peertube"
    at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:184:24)
    at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:305:19)
    at Client._handleErrorMessage (/app/node_modules/pg/lib/client.js:325:19)
    at Connection.emit (events.js:314:20)
    at Connection.EventEmitter.emit (domain.js:483:12)
    at /app/node_modules/pg/lib/connection.js:114:12
    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:40:17)
    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  parent: error: password authentication failed for user "peertube"
      at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (events.js:314:20)
      at Socket.EventEmitter.emit (domain.js:483:12)
      at addChunk (_stream_readable.js:297:12)
      at readableAddChunk (_stream_readable.js:272:9)
      at Socket.Readable.push (_stream_readable.js:213:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
    length: 104,
    severity: 'FATAL',
    code: '28P01',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'auth.c',
    line: '326',
    routine: 'auth_failed'
  },
  original: error: password authentication failed for user "peertube"
      at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (events.js:314:20)
      at Socket.EventEmitter.emit (domain.js:483:12)
      at addChunk (_stream_readable.js:297:12)
      at readableAddChunk (_stream_readable.js:272:9)
      at Socket.Readable.push (_stream_readable.js:213:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
    length: 104,
    severity: 'FATAL',
    code: '28P01',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'auth.c',
    line: '326',
    routine: 'auth_failed'
  }
}
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! peertube@3.2.1 create-transcoding-job: `node ./dist/scripts/create-transcoding-job.js "-v" "73a5cb03-b7ec-4e43-aec7-faa71213bd92" "-r" "420"`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the peertube@3.2.1 create-transcoding-job script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-02T23_55_44_726Z-debug.log
```

meanwhile it works if i do a similar process manually using `docker exec -it u peertube $container_id bash`.

cheers! :purple_heart:

**Comment by decentral1se** [comment] 2021-07-05 16:17
Thanks for raising @ahdinosaur! So nice to see https://tube.arthack.nz :heart: 


Yeah, I ran into this, I've been just doing the `docker exec ...` trick and then running:

```
export NODE_CONFIG_DIR=/config
export NODE_ENV=production
export PEERTUBE_DB_PASSWORD=$(cat /run/secrets/db_password)
npm run ...  # knows where everything is at this point
```

The issue is that our `abra.sh` implementation in:

https://github.com/Coop-Cloud/peertube/blob/406afdb8cff9c617e98c6d8051d7fb6c4f7c3282/abra.sh#L5-L7

doesn't understand that it isn't in the container and shouldn't be asking the local file system for these `/run/` paths...

I will try to get a fix out for this shortly.

**Comment by decentral1se** [comment] 2021-07-06 09:24
Seems to be working now!

https://github.com/Coop-Cloud/peertube/blob/04408f007a1d7bef4505001475c0c34637854132/abra.sh#L6-L15

This required https://github.com/Coop-Cloud/abra/commit/b2e0a95a111ebe24e890993fb6fd64221afd2192 on the `abra` side of things. I also added a `abra app <app> restart <service>` command to make it easy to run restarts of the app service after doing things like pruning storage (required, it seems, otherwise the peertube explodes) but it is only available in an unreleased version right now (see https://git.autonomic.zone/coop-cloud/abra/src/branch/main/CHANGELOG.md#abra-x-x-x-unreleased).

Let me know if you see further issues! I'm gonna close this off for now.

**Closed by decentral1se** 2021-07-06 09:24 UTC
